### PR TITLE
Add support for Unicode characters in TXXX frames

### PR DESCRIPTION
**Pull request by developersthinksmartbox**
Add support for Unicode for TXXX frames

### CODE REVIEW

**Comment by Corey-M** [comment]
Not sure what you changed here because the diff is the entire file.  Did you change the line endings or something on the file?

Can you please submit again with a minimal diff so I can merge.

**Comment by jwallet** [comment]
image

**Comment by Corey-M** [comment]
@jwallet Thanks for that.  I've had a look at the PR and it doesn't compile because he hasn't pushed the required changes to `LameDLLWrap\LimBp3Lame.cs` to support it.

On the plus side, I'm working on those changes.  Will push an update when they are done.

**Comment by Corey-M** [comment]
Oh, and @developersthinksmartbox ... I like pull requests, but two points...

1. Please don't mess with my line endings and white space.
2. Make changes to the files *in the files*, not in copies of the files.

The PR you submitted didn't compile because you added a new `LibMp3Lame.cs` to the project instead of modifying the existing one.

**Comment by Corey-M** [comment]
@developersthinksmartbox This is now resolved.

I wanted to actually test it out so I ended up writing a simple(-ish) ID3v2 tag decoder.  Which told me that the Unicode data wasn't being inserted into the tag.  It turns out that the lame code /requires/ that all UTF-16 strings have the Byte Order Marker headers.  Took some messing around to find out exactly what the problem was there.  Fortunately I can still read /some/ C code.

Check out v1.0.8 and let me know what you think.  If it still doesn't do what you need then open an issue.

**Pull request closed without merging**
